name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: make test

    - name: Run GoReleaser (dry-run)
      uses: goreleaser/goreleaser-action@v2
      with:
        args: release --rm-dist --skip-publish --snapshot
